
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
//import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author felix
 */
public class FormData4 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormData4.class.getName());

    /**
     * Creates new form FormData4
     */
    public FormData4() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(255, 125, 0));
        jPanel1.setBackground(new java.awt.Color(255, 125, 0, 125));

        jLabel1.setBackground(new java.awt.Color(255, 123, 0));
        jLabel2.setBackground(new java.awt.Color(255, 123, 0));
        jLabel3.setBackground(new java.awt.Color(255, 123, 0));

        jLabel1.setOpaque(true);
        jLabel2.setOpaque(true);
        jLabel3.setOpaque(true);

        String NOMBRE = "Pedro";
        String APODO = "La Roka";
        String APELLIDO = "Diaz";
        Data1.setText(NOMBRE);
        Data2.setText(APODO);
        Data3.setText(APELLIDO);

        ImageIcon imagen1 = new ImageIcon(getClass().getResource("Images/2.jpg"));
        Icon fondo1;
        fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(lblimage1.getWidth(), lblimage1.getHeight(), Image.SCALE_DEFAULT));
        lblimage1.setIcon(fondo1);
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Data1 = new javax.swing.JTextField();
        Data2 = new javax.swing.JTextField();
        Data3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        lblimage1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Data1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        Data1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data1ActionPerformed(evt);
            }
        });
        jPanel1.add(Data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 110, 40));

        Data2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        Data2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data2ActionPerformed(evt);
            }
        });
        jPanel1.add(Data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 110, 40));

        Data3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        Data3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data3ActionPerformed(evt);
            }
        });
        jPanel1.add(Data3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 110, 40));

        jLabel1.setBackground(new java.awt.Color(0, 132, 255));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 132, 255));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 132, 255));
        jLabel2.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 132, 255));
        jLabel2.setText("Apodo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 132, 255));
        jLabel3.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 132, 255));
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        next.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        next.setText("Calculadora de Años");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 220, 40));
        jPanel1.add(lblimage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 140));

        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Data1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data1ActionPerformed

    private void Data2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data2ActionPerformed

    private void Data3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data3ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        

        this.setVisible(false);

        this.revalidate();
        this.repaint();

       FormCalc3 calcc = new FormCalc3();
        calcc.setVisible(true);

    }//GEN-LAST:event_nextActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormData4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Data1;
    private javax.swing.JTextField Data2;
    private javax.swing.JTextField Data3;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblimage1;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
